# Generated by Django 4.0.2 on 2022-02-24 19:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Details',
        ),
    ]
