# Generated by Django 4.0.2 on 2022-02-24 20:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0002_rename_form_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Form',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='user',
            new_name='user_id',
        ),
    ]
