# Generated by Django 4.0.2 on 2022-02-25 08:01

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_rename_details_form_rename_user_form_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='address',
            field=models.CharField(default='not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='bid',
            field=models.CharField(choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')], default='not specified', max_length=6),
        ),
        migrations.AlterField(
            model_name='form',
            name='company_name',
            field=models.CharField(default='not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='dob',
            field=models.DateField(default='not specified'),
        ),
        migrations.AlterField(
            model_name='form',
            name='first_name',
            field=models.CharField(default='not specified', max_length=20),
        ),
        migrations.AlterField(
            model_name='form',
            name='google_id',
            field=models.BigIntegerField(default='not specified'),
        ),
        migrations.AlterField(
            model_name='form',
            name='surname',
            field=models.CharField(default='not specified', max_length=20),
        ),
        migrations.AlterField(
            model_name='form',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='not specified', max_length=17, region=None, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(default='not specified', max_length=20),
        ),
    ]
