# Generated by Django 4.0.2 on 2022-02-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_form_address_alter_form_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='details_complete',
        ),
        migrations.AlterField(
            model_name='form',
            name='google_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
