# Generated by Django 4.0.2 on 2022-02-25 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_remove_form_details_complete_alter_form_google_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='form',
            name='google_id',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
