# Generated by Django 4.0.2 on 2022-02-26 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_alter_form_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='google_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
