# Generated by Django 4.0.2 on 2022-02-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_alter_form_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='address',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='form',
            name='company_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='form',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='form',
            name='surname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
